### ISSUE TITLE
TypeError after Get request to  '/ledger/entity/create/' with all the optional fields checked.

### ISSUE THREAD

**Issue by Sourabhpatel1** [arrobalytics/django-ledger#118]
**Describe the bug**
`TypeError:` InvoiceModelAbstract.update_amount_due() got an unexpected keyword argument 'itemtxs_list'
TypeError after Get request to  '/ledger/entity/create/' with all the optional fields checked.

**To Reproduce**
1. Go to 'localhost:8000/ledger/entity/create'
2. fill necessary details.
3. Click on 'Create'
5. See error on webpage if in debug mode or in the terminal

**Expected behavior**
An entity should be created with dummy data already populated

**Desktop (please complete the following information):**
 - OS: Fedora Linux 37 
 - Browser: FireFox 
 - Version: 106

**Additional context**
***Full Stack Trace***
Traceback (most recent call last):
  File "/home/sourabh/Project/env/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/sourabh/Project/env/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sourabh/Project/env/lib/python3.11/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sourabh/Project/env/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 109, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/sourabh/Project/env/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/sourabh/Project/env/lib/python3.11/site-packages/django/views/generic/base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/sourabh/Project/env/lib/python3.11/site-packages/django/views/generic/edit.py", line 184, in post
    return super().post(request, *args, **kwargs)
  File "/home/sourabh/Project/env/lib/python3.11/site-packages/django/views/generic/edit.py", line 153, in post
    return self.form_valid(form)
  File "/home/sourabh/Project/env/lib/python3.11/site-packages/django_ledger/views/entity.py", line 98, in form_valid
    entity_generator.populate_entity()
  File "/home/sourabh/Project/env/lib/python3.11/site-packages/django_ledger/io/data_generator.py", line 135, in populate_entity
    self.create_invoice(date_draft=start_dttm)
  File "/home/sourabh/Project/env/lib/python3.11/site-packages/django_ledger/io/data_generator.py", line 653, in create_invoice
    invoice_model.update_amount_due(itemtxs_list=invoice_items)

Exception Type: TypeError at /ledger/entity/create/
Exception Value: InvoiceModelAbstract.update_amount_due() got an unexpected keyword argument 'itemtxs_list'

**Comment by elarroba** [comment]
@Sourabhpatel1 please update to latest version v0.5.2.4 tag just released. Let me know if the bug has been resolved.

**Comment by Sourabhpatel1** [comment]
Will do. Thanks for the update.

**Comment by elarroba** [comment]
This bug should be fixed by now.
