### ISSUE TITLE
test failure : FAIL: test_bill_detail (django_ledger.tests.test_bill.BillModelTests.test_bill_detail)

### ISSUE THREAD

**Issue by tolland** [arrobalytics/django-ledger#221]
**Describe the bug**
Run the tests from the develop branch some are failing, this one on a template issue:
```
$ python manage.py test django_ledger.tests.test_bill.BillModelTests.test_bill_detail
Found 1 test(s).
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
08/03/2024 01:19:00 AM Populating Entity Testing Inc-626038...
F
======================================================================
FAIL: test_bill_detail (django_ledger.tests.test_bill.BillModelTests.test_bill_detail)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user1/git/django-ledger/django_ledger/tests/test_bill.py", line 370, in test_bill_detail
    self.assertContains(bill_detail_response, 'id="djl-bill-detail-amount-owed"')
  File "/home/user1/.local/share/virtualenvs/django-ledger-azuD17Ir/lib/python3.11/site-packages/django/test/testcases.py", line 537, in assertContains
    self.assertTrue(
AssertionError: False is not true : Couldn't find 'id="djl-bill-detail-amount-owed"' in response

----------------------------------------------------------------------
Ran 1 test in 11.594s
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser firefox

**Smartphone (please complete the following information):**

**Additional context**

**Comment by tolland** [comment]
It's happening because the string its looking for is in the conditional block that requires the bill model to be `accrue == True`
https://github.com/arrobalytics/django-ledger/blob/develop/django_ledger/templates/django_ledger/bills/bill_detail.html#L68-L76

**Comment by tolland** [comment]
https://github.com/arrobalytics/django-ledger/pull/222/files
