### ISSUE TITLE
JSONField package is not imported

### ISSUE THREAD

**Issue by Inshaal93** [arrobalytics/django-ledger#30]
**Describe the bug**
JSONField package is not installed with requirements and not imported in models.

**To Reproduce**
1. `pip install git+https://github.com/arrobalytics/django-ledger.git`
2. Add to installed apps:
```
INSTALLED_APPS = [
    ...,
    'django_ledger',
    ...,
]
```
3. Start server wit `python3 manage.py runserver`

**Expected behavior**
Server should start up without errors.

**Logs**
```
> python3 manage.py runserver
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/usr/local/lib/python3.8/site-packages/django/utils/autoreload.py", line 76, in raise_last_exception

    raise _exception[1]
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 357, in execute
    autoreload.check_errors(django.setup)()
  File "/usr/local/lib/python3.8/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.8/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/usr/local/lib/python3.8/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/site-packages/django_ledger/models/__init__.py", line 19, in <module>
    from django_ledger.models.customer import CustomerModel
  File "/usr/local/lib/python3.8/site-packages/django_ledger/models/customer.py", line 32, in <module>
    class CustomerModel(ContactInfoMixIn, CreateUpdateMixIn):
  File "/usr/local/lib/python3.8/site-packages/django_ledger/models/customer.py", line 43, in CustomerModel
    additional_info = models.JSONField(null=True, blank=True)
AttributeError: module 'django.db.models' has no attribute 'JSONField'

```

**Desktop info:**
 - OS: macOS Catalina

**Comment by elarroba** [comment]
@Inshaal93 Which version of Django are you running?
JSONField is supported starting with version 3.1.
https://docs.djangoproject.com/en/3.1/ref/models/fields/#jsonfield

**Comment by elarroba** [comment]
@Inshaal93 did you resolve your issue upgrading Django?

**Comment by Inshaal93** [comment]
Sorry, didn't get to try again. Will test soon and let you know.

**Comment by elarroba** [comment]
Closing this issue because of lack of response.

**Comment by Inshaal93** [comment]
To close the loop on this, yes, it was because I wasn't using Django 3.1+
