### ISSUE TITLE
"Fill WIth Sample Data" throws 500

### ISSUE THREAD

**Issue by Inshaal93** [arrobalytics/django-ledger#43]
**Describe the bug**
When creating a new entity, if you select the "Fill With Sample Data" option, you get forwarded to an error page.
The entity will be created but there is not data inside. 
If you refresh the page, you still see an error but another entity is created.

**To Reproduce**
1. Create New Entity with "Fill With Sample Data" selected
2. Select 'Create'
3. Error:
```
Internal Server Error: /ledger/entity/create/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 73, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/mixins.py", line 52, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/edit.py", line 172, in post
    return super().post(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/edit.py", line 142, in post
    return self.form_valid(form)
  File "/usr/local/lib/python3.8/site-packages/django_ledger/views/entity.py", line 72, in form_valid
    generate_sample_data(
  File "/usr/local/lib/python3.8/site-packages/django_ledger/utils.py", line 266, in generate_sample_data
    capital_acc = choice(accounts_gb['eq_capital'])
KeyError: 'eq_capital'
[09/Jan/2021 04:38:16] "POST /ledger/entity/create/ HTTP/1.1" 500 100178
```
**Expected behavior**
A new entity to be created with a set of sample data.

**Screenshots**
![image](https://user-images.githubusercontent.com/45584256/104083293-45357980-51f2-11eb-9866-40c8bd2891f6.png)

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Browser: Chrome
 - Version v0.4.0.1

**Comment by elarroba** [comment]
@Inshaal93 thank you for staring this issue. Can you please try to select all 3 options:

- Populate Default CoA (Code of Accounts)
- Activate Accounts
- Fill With Sample Data

This needs to be addressed as a form validation issue since you cannot fill the entity with sample data if there are no accounts available to use (therefore the need to create a CoA and Activate accounts). Please try this approach and kindly give some feedback.

Thanks
Miguel
