### ISSUE TITLE
Getting TypeError: 'type' object is not subscriptable :while migration first time 

### ISSUE THREAD

**Issue by rashed-imam** [arrobalytics/django-ledger#53]
I am getting  This Type error wile migration first time

- Windows
- python 3.8.7
- Django 3.1

```
   from django_ledger.utils import set_default_entity
  File "C:\Users\User\Documents\sandbox\env\lib\site-packages\django_ledger\utils.py", line 65, in <module>
    bill_desc: str = None) -> tuple[LedgerModel, BillModel]:
TypeError: 'type' object is not subscriptable
```

Full Version:

`(env) C:\Users\User\Documents\sandbox\env\hishab>python manage.py migrate django_ledger
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\User\Documents\sandbox\env\lib\site-packages\django\core\management\__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "C:\Users\User\Documents\sandbox\env\lib\site-packages\django\core\management\__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\User\Documents\sandbox\env\lib\site-packages\django\core\management\base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\User\Documents\sandbox\env\lib\site-packages\django\core\management\base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "C:\Users\User\Documents\sandbox\env\lib\site-packages\django\core\management\base.py", line 85, in wrapped
    res = handle_func(*args, **kwargs)
  File "C:\Users\User\Documents\sandbox\env\lib\site-packages\django\core\management\commands\migrate.py", line 75, in handle
    self.check(databases=[database])
  File "C:\Users\User\Documents\sandbox\env\lib\site-packages\django\core\management\base.py", line 392, in check
    all_issues = checks.run_checks(
  File "C:\Users\User\Documents\sandbox\env\lib\site-packages\django\core\checks\registry.py", line 70, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "C:\Users\User\Documents\sandbox\env\lib\site-packages\django\core\checks\urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "C:\Users\User\Documents\sandbox\env\lib\site-packages\django\core\checks\urls.py", line 23, in check_resolver
    return check_method()
  File "C:\Users\User\Documents\sandbox\env\lib\site-packages\django\urls\resolvers.py", line 408, in check
    for pattern in self.url_patterns:
  File "C:\Users\User\Documents\sandbox\env\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\User\Documents\sandbox\env\lib\site-packages\django\urls\resolvers.py", line 589, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Users\User\Documents\sandbox\env\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\User\Documents\sandbox\env\lib\site-packages\django\urls\resolvers.py", line 582, in urlconf_module
    return import_module(self.urlconf_name)
  File "c:\users\user\appdata\local\programs\python\python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\User\Documents\sandbox\env\hishab\hishab\urls.py", line 21, in <module>
    path('ledger/', include('django_ledger.urls', namespace='django_ledger')),
  File "C:\Users\User\Documents\sandbox\env\lib\site-packages\django\urls\conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "c:\users\user\appdata\local\programs\python\python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\User\Documents\sandbox\env\lib\site-packages\django_ledger\urls\__init__.py", line 11, in <module>
    from django_ledger import views
  File "C:\Users\User\Documents\sandbox\env\lib\site-packages\django_ledger\views\__init__.py", line 9, in <module>
    from django_ledger.views.account import *
  File "C:\Users\User\Documents\sandbox\env\lib\site-packages\django_ledger\views\account.py", line 19, in <module>
    from django_ledger.views.mixins import (
  File "C:\Users\User\Documents\sandbox\env\lib\site-packages\django_ledger\views\mixins.py", line 25, in <module>
    from django_ledger.utils import set_default_entity
  File "C:\Users\User\Documents\sandbox\env\lib\site-packages\django_ledger\utils.py", line 65, in <module>
    bill_desc: str = None) -> tuple[LedgerModel, BillModel]:
TypeError: 'type' object is not subscriptable`

**Comment by rangacs** [comment]
Am also getting same error, how can we resolve this issue?

**Comment by n0tNoah** [comment]
got the same error just temporary remove the 
`-> tuple[LedgerModel, BillModel]` on django_ledger/utils.py", line 65

**Comment by elarroba** [comment]
@rangacs @n0tNoah I have corrected this bug.
